global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'zapunk1@gmail.com'
  smtp_auth_username: 'zapunk1@gmail.com'
  smtp_auth_password: '${SMTP_PASS}'

route:
  receiver: 'email-and-telegram'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
- name: 'email-and-telegram'
  email_configs:
    - to: 'zapunk1@gmail.com'
      send_resolved: true

  telegram_configs:
    - bot_token: '${TG_BOT_TOKEN}'
      chat_id: 1306744343
      parse_mode: HTML
      send_resolved: true
