server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s

    relabel_configs:
      # Путь к логам
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/*.log

      # Swarm метки
      - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
        target_label: stack
      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: service

      # Базовые метки
      - source_labels: [__meta_docker_container_name]
        target_label: container

      # Обязательные метки
      - target_label: job
        replacement: docker
      - target_label: host
        replacement: docker-host

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time

      - labels:
          stream:

      - labeldrop:
          - filename
          - __meta_docker_container_label_
          - attrs
          - stream

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: log
