global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'my_services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'gateway-service:8087'
          - 'session-service:8081'
          - 'booking-service:8083'
          - 'report-service:8086'

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'cadvisor:8080'
        labels:
          job: 'cadvisor'
          app: 'monitoring'

  - job_name: node_exporter
    dns_sd_configs:
      - names:
          - tasks.monitoring_node_exporter
        type: A
        port: 9100

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://www.google.com
          - http://gateway-service:8087
          - http://booking-service:8083

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115