- name: Установить Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Запустить Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Создать тестовую страницу
  copy:
    content: "YUHHU!!! Apache already work!"
    dest: /var/www/html/index.html