apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: zapunk1/s21-hotel:v2
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: my-config
            - secretRef:
                name: my-secrets
          env:
            - name: POSTGRES_DB
              value: hotels_db
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - port: 8082
      targetPort: 8082
