apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - postgres.yml
  - postgres-initdb.yml
  - rabbitmq.yml
  - secrets.yml
  - services/booking.yml
  - services/gateway.yml
  - services/hotel.yml
  - services/loyalty.yml
  - services/payment.yml
  - services/report.yml
  - services/session.yml